version: '3.3'

services:
        app:
                image: nocobase/nocobase:main
                container_name: nocobase
                depends_on:
                        - postgres
                environment:
                        - DB_DIALECT=postgres
                        - DB_HOST=postgres
                        - DB_DATABASE=nocobase
                        - DB_USER=nocobase
                        - DB_PASSWORD=nocobase
                        - LOCAL_STORAGE_BASE_URL=/storage/uploads
                volumes:
                        - ./storage:/app/nocobase/storage
                        - ./plugins/custom-popup-action:/app/nocobase/plugins/custom-popup-action
                ports:
                        - '8200:80'
                restart: unless-stopped

        postgres:
                image: postgres:latest
                container_name: nocobase-db
                command: postgres -c wal_level=logical
                ports:
                        - '5432:5432'
                volumes:
                        - ./storage/db/postgres/backups:/backups
                environment:
                        - POSTGRES_USER=nocobase
                        - POSTGRES_DB=nocobase
                        - POSTGRES_PASSWORD=nocobase
                restart: unless-stopped
